### ISSUE TITLE
Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers

### ISSUE THREAD

**Issue by JakobStadlhuber** [sglvladi/TensorFlowObjectDetectionTutorial#100]
I have a problem with running the final test on an Intel Mac (CPU)
```
(tensorflow) jakob@MacBook-Pro-von-Jakob research % python object_detection/builders/model_builder_tf2_test.py
2021-11-04 12:57:25.413405: E tensorflow/core/lib/monitoring/collection_registry.cc:77] Cannot register 2 metrics with the same name: /tensorflow/api/keras/optimizers
Traceback (most recent call last):
  File "/Users/jakob/Documents/TensorFlow/models/research/object_detection/builders/model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/object_detection/builders/model_builder.py", line 25, in <module>
    from object_detection.builders import box_predictor_builder
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/object_detection/builders/box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/object_detection/predictors/convolutional_box_predictor.py", line 26, in <module>
    from object_detection.core import box_predictor
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/object_detection/core/box_predictor.py", line 137, in <module>
    class KerasBoxPredictor(tf.keras.layers.Layer):
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 62, in __getattr__
    module = self._load()
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/metrics.py", line 26, in <module>
    from keras import activations
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/activations.py", line 20, in <module>
    from keras.layers import advanced_activations
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/layers/__init__.py", line 23, in <module>
    from keras.engine.input_layer import Input
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/engine/input_layer.py", line 21, in <module>
    from keras.engine import base_layer
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 18, in <module>
    from keras import optimizers
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/optimizers.py", line 26, in <module>
    from keras.optimizer_v2 import adadelta as adadelta_v2
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/optimizer_v2/adadelta.py", line 22, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 36, in <module>
    keras_optimizers_gauge = tf.__internal__.monitoring.BoolGauge(
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 360, in __init__
    super(BoolGauge, self).__init__('BoolGauge', _bool_gauge_methods,
  File "/Users/jakob/opt/anaconda3/envs/tensorflow/lib/python3.9/site-packages/tensorflow/python/eager/monitoring.py", line 135, in __init__
    self._metric = self._metric_methods[self._label_length].create(*args)
tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.
```

**Comment by JakobStadlhuber** [comment]
https://stackoverflow.com/questions/69694944/how-to-fix-error-cannot-register-2-metrics-with-the-same-name-tensorflow-api/69831814

**Comment by JakobStadlhuber** [comment]
Fix for me: do not use pipfor pycocotools instead use:
```
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
make
cp -r pycocotools <PATH_TO_TF>/TensorFlow/models/research/
```
