### ISSUE TITLE
NO CHECKPOINT SPECIFIED

### ISSUE THREAD

**Issue by jenapss** [sglvladi/TensorFlowObjectDetectionTutorial#39]
```
File "exporter_main_v2.py", line 126, in <module>
    app.run(main)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "exporter_main_v2.py", line 122, in main
    FLAGS.output_directory)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/exporter_lib_v2.py", line 172, in export_inference_graph
    status.assert_existing_objects_matched()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 877, in assert_existing_objects_matched
    "No checkpoint specified (save_path=None); nothing is being restored.")
AssertionError: No checkpoint specified (save_path=None); nothing is being restored.``
```

Getting this error when running `exporter_main_v2.py`. I specified all needed directories but dunno yet why it says No Checkpoint specified. Who knows the workaround for this?

**Comment by sglvladi** [comment]
@jenapss can you please provide the full command you are trying to run?

**Comment by jenapss** [comment]
**Sure. Here it is full output with command and log. Command is:** 
`jelaleddin@jelaleddins-MacBook-Pro training_demo % python exporter_main_v2.py \
    --input_type image_tensor \
    --pipeline_config_path ./models/my_ssd_mobilenet/pipeline.config \
    --trained_checkpoint_dir ./models/my_ssd_mobilenet/ckpt-1.data-00000-of-00001 \
    --output_directory ./exported-models/my_model `


**Full log :**
`jelaleddin@jelaleddins-MacBook-Pro training_demo % python exporter_main_v2.py \
    --input_type image_tensor \
    --pipeline_config_path ./models/my_ssd_mobilenet/pipeline.config \
    --trained_checkpoint_dir ./models/my_ssd_mobilenet/ckpt-1.data-00000-of-00001 \
    --output_directory ./exported-models/my_model      
2020-07-31 23:00:19.192775: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-31 23:00:19.205567: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x13c3ac480 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-31 23:00:19.205587: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.257697 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.257997 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.258183 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.258404 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.258591 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
I0731 23:00:28.258830 140734943485248 convolutional_keras_box_predictor.py:154] depth of additional conv before box predictor: 0
Traceback (most recent call last):
  File "exporter_main_v2.py", line 126, in <module>
    app.run(main)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "exporter_main_v2.py", line 122, in main
    FLAGS.output_directory)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/exporter_lib_v2.py", line 172, in export_inference_graph
    status.assert_existing_objects_matched()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 877, in assert_existing_objects_matched
    "No checkpoint specified (save_path=None); nothing is being restored.")
AssertionError: No checkpoint specified (save_path=None); nothing is being restored.`

**Comment by sglvladi** [comment]
Ahh I see, the problem is in the parameter passed to ``--trained_checkpoint_dir``. You are used to the TF1 version where you had to specify the exact path to the checkpoint file. Instead, just specify the path to the dir containing the file.

Try running this:

```
python exporter_main_v2.py \
    --input_type image_tensor \
    --pipeline_config_path ./models/my_ssd_mobilenet/pipeline.config \
    --trained_checkpoint_dir ./models/my_ssd_mobilenet/ \
    --output_directory ./exported-models/my_model       
```

Notice I have removed the ``ckpt-1.data-00000-of-00001`` bit from the ``--trained_checkpoint_dir`` value. 

Hope this helps.

**Comment by jenapss** [comment]
Cool! It worked! Thank you so much!
