### ISSUE TITLE
checkpoint_management UnicodeDecodeError: 'utf-8'

### ISSUE THREAD

**Issue by rnrllah07** [sglvladi/TensorFlowObjectDetectionTutorial#52]
hi i tried your tutorial. thanks alot.

My problem when start training checkpoint management cant read my checkpoint. 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 108: invalid start byte

you can see my problem on stackoverflow: 

https://stackoverflow.com/questions/63910511/error-while-training-tensorflow-object-detection-about-checkpoint-error

Please help me

**Comment by jung-sang** [comment]
check the path, Tutorial isnt 100% correct

**Comment by sglvladi** [comment]
@rnrllah07 Please try running the command in  Windows Powershell, rather than in Command Prompt. Does this make any difference?

**Comment by rnrllah07** [comment]
@sglvladi  ı tried powershel but ı cant activate anaconda. ı tried that

**Comment by rnrllah07** [comment]
@jung-sang ı am sure right path.

**Comment by rnrllah07** [comment]
@sglvladi @jung-sang  do you help me with zoom or other ways? please

**Comment by sglvladi** [comment]
@jung-sang Can I please ask you to explain how you fixed your issues in #51? Your help would be much appreciated

**Comment by jung-sang** [comment]
@rnrllah07 @sglvladi i tried three models, 'Faster R-CNN Inception ResNet V2 1024x1024', 'SSD MobileNet V2 FPNLite 640x640' and 'SSD ResNet50 V1 FPN 640x640 (RetinaNet50)', first two models worked fine but last one which was used for @sglvladi tutorial didnt work on my desktop either , showing the same error code 'utf-8'
plz try some other models and let me know

**Comment by rnrllah07** [comment]
@jung-sang  thank you for feedback. ı used "ssd_resnet101_v1_fpn_1024x1024_coco17_tpu-8" and "efficientdet_d7_coco17_tpu-32" models for training. ı will try with "Faster R-CNN Inception ResNet V2 1024x1024" and 'SSD MobileNet V2 FPNLite 640x640'. And ı will write here. see you again.  if you solve with my used models, please write here again. thank you

**Comment by rnrllah07** [comment]
@jung-sang @sglvladi   I tried with "Faster R-CNN Inception ResNet V2 1024x1024" and it is not working with same error.  ı dont know what will ı do :((

**Comment by rnrllah07** [comment]
Traceback (most recent call last):
  File "model_main_tf2.py", line 113, in <module>
    tf.compat.v1.app.run()
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "model_main_tf2.py", line 110, in main
    record_summaries=FLAGS.record_summaries)
  File "C:\TensorFlow\models\research\object_detection\model_lib_v2.py", line 578, in train_loop
    ckpt, manager_dir, max_to_keep=checkpoint_max_to_keep)
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 635, in __init__
    recovered_state = get_checkpoint_state(directory)
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\checkpoint_management.py", line 279, in get_checkpoint_state
    coord_checkpoint_filename)
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 320, in read_file_to_string
    return f.read()
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 116, in read
    self._preread_check()
  File "C:\Users\Nurullah\.conda\envs\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 133: invalid start byte

**Comment by JH-Peter-Park** [comment]
did you solve this issue?
